/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DNS_H_RPCGEN
#define _DNS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct registrar_1_argument {
	char *arg1;
	char *arg2;
};
typedef struct registrar_1_argument registrar_1_argument;

struct modificar_1_argument {
	char *arg1;
	char *arg2;
	int arg3;
};
typedef struct modificar_1_argument modificar_1_argument;

#define DNSPROG 0x20000199
#define DNSCVER 1
#define DNS2PROG 0x20000200
#define DNS2CVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrar 1
extern  int * registrar_1(char *, char *, CLIENT *);
extern  int * registrar_1_svc(char *, char *, struct svc_req *);
#define eliminar 2
extern  int * eliminar_1(char *, CLIENT *);
extern  int * eliminar_1_svc(char *, struct svc_req *);
#define buscar 3
extern  char ** buscar_1(char *, CLIENT *);
extern  char ** buscar_1_svc(char *, struct svc_req *);
#define modificar 4
extern  int * modificar_1(char *, char *, int , CLIENT *);
extern  int * modificar_1_svc(char *, char *, int , struct svc_req *);
extern int dnsprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
extern int dns2prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
#else /* K&R C */
#define registrar 1
extern  int * registrar_1();
extern  int * registrar_1_svc();
#define eliminar 2
extern  int * eliminar_1();
extern  int * eliminar_1_svc();
#define buscar 3
extern  char ** buscar_1();
extern  char ** buscar_1_svc();
#define modificar 4
extern  int * modificar_1();
extern  int * modificar_1_svc();
extern int dnsprog_1_freeresult ();
extern int dns2prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registrar_1_argument (XDR *, registrar_1_argument*);
extern  bool_t xdr_modificar_1_argument (XDR *, modificar_1_argument*);

#else /* K&R C */
extern bool_t xdr_registrar_1_argument ();
extern bool_t xdr_modificar_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DNS_H_RPCGEN */
